vm:
  name: oscar-ci
  spec: vm/cloud-init.yaml
  cpus: 4
  mem: 8G
  disk: 20G
  image: "18.04"
  ci-repo: https://github.com/oscar-system/oscar-ci
  # The "branch" entry is optional and defaults to "master".
  branch: master
  # If set to true, jobs will pull their meta repo from the "ci-repo"
  # setting instead of what is specified in their Jenkinsfile.
  redirect-jobs: false
jenkins:
  user: jenkins
  passwd: jenkins
jobs:
  oscar:
    parameters:
    - name: JULIA_VERSION
      string: "download:1.4.2"
      desc: >
        Which branch of Julia to build? This can be a git branch name,
        a git tag prefixed by "tag:" or a version number prefixed by
        "download:" to grab a tarball directly.
      # Alternative version specs accepted for the Julia installation:
      # string: "tag:v1.4.2"
      # string: "master"
    - name: GAP_VERSION
      string: master
      desc: >
        Which branch of GAP to track? (We will not actually build this
        version, this is just to track commits.)
    - name: BUILDTYPE
      options:
      - master
      - stable
      - develop
      desc: >
        Whether to build the current stable tagged versions or the
        master branches. The develop & master options vary in the
        order in which dependencies are installed, with develop mode
        trying to install dependencies before packages that use them.
    - name: BUILDJOBS
      string: 4
    - name: REBUILDMODE
      options:
      - normal
      - full
      - none
      desc: >
        Whether to do a full rebuild, an incremental build, or to
        skip rebuilding and go straight to tests.
    - name: NODE_LABEL
      string: master
      desc: >
        Which nodes to run this job on.
    - name: DOCKERIZE
      options:
      - "no"
      - "yes"
      desc: >
        Whether to run tests within a docker container.
    # The "timer" entry is optional and should only be used if the job should
    # run at the specified timer intervals.
    #
    # timer:
    #   "H/30 * * * *"
    #
    # The "jenkinsfile" entry is optional. If omitted entirely or in
    # part, the value are taken from the vm section for the repo and
    # the branch and default to "Jenkinsfile" for the path.
    #
    # jenkinsfile:
    #   repo: https://github.com/oscar-system/oscar
    #   branch: master
    #   path: Jenkinsfile
  oscar-stable:
    parameters:
    - name: JULIA_VERSION
      string: "download:1.4.2"
      desc: >
        Which branch of Julia to build?
    - name: GAP_VERSION
      string: master
      desc: >
        Which branch of GAP to track?
    - name: BUILDTYPE
      options:
      - stable
      - master
      - develop
      desc: >
        Whether to build the current stable tagged versions or the
        master branches. The develop & master options vary in the
        order in which dependencies are installed, with develop mode
        trying to install dependencies before packages that use them.
    - name: BUILDJOBS
      string: 4
    - name: REBUILDMODE
      options:
      - normal
      - full
      - none
      desc: >
        Whether to do a full rebuild, an incremental build, or to
        skip rebuilding and go straight to tests.
    - name: NODE_LABEL
      string: master
      desc: >
        Which nodes to run this job on.
    - name: DOCKERIZE
      options:
      - "no"
      - "yes"
      desc: >
        Whether to run tests within a docker container.
    # The "timer" entry is optional and should only be used if the job should
    # run at the specified timer intervals.
    #
    # timer:
    #   "H/30 * * * *"
    #
    # The "jenkinsfile" entry is optional. If omitted entirely or in
    # part, the value are taken from the vm section for the repo and
    # the branch and default to "Jenkinsfile" for the path.
    #
    # jenkinsfile:
    #   repo: https://github.com/oscar-system/oscar
    #   branch: master
    #   path: Jenkinsfile

