packages:
- autoconf
- automake
- curl
- cython
- cython3
- default-jdk
- dnsutils
- docker.io
- g++
- gcc
- gdb
- gfortran
- git
- host
- inetutils-ping
- inetutils-traceroute
- libtool-bin
- locales
- make
- mercurial
- net-tools
- ninja-build
- pandoc
- perl
- python
- python-dev
- python3
- python3-dev
- python3-venv
- python3-yaml
- ruby
- ruby-dev
- screen
- subversion
- tmux
- vim
- wget
- zsh
groups:
- docker
runcmd:
  - "usermod -a -G docker ubuntu"
